### ISSUE TITLE
Create signup/login page

### ISSUE THREAD

**Issue by Andymendez100** [Andymendez100/YDEKM#18] opened 2019-09-14 05:01 UTC
These need to be on the same page. Check google docs for example. 

Sign up 👍                                               Login:
email:                                                        username:
username:                                                 password"
password:
confirm password:

**Comment by dhuan008** [comment] 2019-09-14 05:06
Duplicate of issue #15 ?

**Comment by saynegrojas** [comment] 2019-09-14 05:12
Yes. It's the same

**Closed** 2019-09-14 05:17 UTC
